se is nu rnu bs=2 ru mouse=a encoding=utf-8
se cin et sw=4 sts=4 t_Co=256 tgc sc hls ls=2
syn on
colorscheme desert
filetype indent on
inoremap {<CR> {<CR>}<ESC>O
map <F8> <ESC>:w<CR>:!clear && g++ "%" -o "%<" -fsanitize=address -fsanitize=undefined -g && echo success<CR>
map <F9> <ESC>:w<CR>:!clear && g++ "%" -o "%<" -O2 && echo success<CR>
map <F10> <ESC>:!./"%<"<CR>
