se is nu ru et tgc sc hls cin cino+=j1 sw=2 sts=2 bs=2 mouse=a "encoding=utf-8 ls=2
syn on | colo desert | filetype indent on
inoremap {<CR> {<CR>}<ESC>O
map <F8> <ESC>:w<CR>:!g++ "%" -o "%<" -g -std=gnu++20 -DCKISEKI -Wall -Wextra -Wshadow -Wfatal-errors -Wconversion -fsanitize=address,undefined,float-divide-by-zero,float-cast-overflow && echo success<CR>
map <F9> <ESC>:w<CR>:!g++ "%" -o "%<" -O2 -g -std=gnu++20 && echo success<CR>
map <F10> <ESC>:!./"%<"<CR>
ca Hash w !cpp -dD -P -fpreprocessed \| tr -d "[:space:]" \| md5sum \| cut -c-6
let c_no_curly_error=1
" setxkbmap -option caps:ctrl_modifier
