---
babel-lang: chinese-traditional
CJKmainfont: "jf-openhuninn-1.1"
CJKoptions:
  - Path=../pdf/fonts/open-huninn-font/
mainfont: "SourceCodePro-Regular"
mainfontoptions:
  - Path=../pdf/fonts/SourceCodePro/,
  - BoldFont=SourceCodePro-Black,
  - ItalicFont=SourceCodePro-Italic,
  - BoldItalicFont=SourceCodePro-BlackItalic,
pdfa: yes
geometry: margin=1.5cm
colorlinks: true
urlcolor: blue
# linkcolor: red
# toccolor: orange
header-includes:
  - \special {pdf:trailerid [ <00112233445566778899aabbccddeeff> <00112233445566778899aabbccddeeff> ]}
    # https://github.com/jgm/pandoc/issues/6539
  - \usepackage{xeCJKfntef}
  - \usepackage[most,breakable]{tcolorbox}
  - \definecolor{textttBoxColor}{HTML}{EEEEEE}
  - \renewcommand{\texttt}[1]{\colorbox{textttBoxColor}{\tt{#1}}}
---
