# This is a basic workflow to help you get started with Actions

name: build docs.pdf

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
      - 'docs/*.md'
      - '.github/workflows/*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docs:
    name: build docs.pdf and commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils
      - name: Install md-to-pdf
        run: npm i -g md-to-pdf
      - name: Build PDF
        run: |
          bash -c "cd docs/ && printf \"---\\nscript:\\n  - path: mathjax-config.js\\n  - url: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js\\n---\\n\" | cat - Basic.md DataStructure.md FlowAndMatching.md Graph.md Math.md Geometry.md String.md Misc.md | md-to-pdf --launch-options '{ \"args\": [\"--no-sandbox\", \"--disable-setuid-sandbox\"] }' > docs.pdf"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: auto build docs - ${{ github.sha }}
