# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/docs.pdf'
      - 'pdf/codebook.pdf'
      - 'README.md'
      - '.editorconfig'

env:
  SOURCE_DATE_EPOCH: 0 # reproducible latex build

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  all:
    name: build and commit
    runs-on: ubuntu-latest
    container: ghcr.io/omeletwithoutegg/ckiseki/builder:master
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Trust Directory
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          # https://github.com/actions/checkout/issues/760
      - name: Build codebook
        working-directory: pdf
        run: make clean && make codebook.pdf
      - name: Build docs
        working-directory: docs
        run: make clean && make docs.pdf
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: auto build - ${{ github.sha }}
