# This is a basic workflow to help you get started with Actions

name: build codebook.pdf

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - 'pdf/codebook.pdf'
      - 'README.md'
      - '.editorconfig'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  codebook:
    name: build and commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cpp latexmk texlive-lang-chinese texlive-science texlive-xetex
      - name: Build PDF
        run: |
          cd pdf/ && latexmk --xelatex --shell-escape codebook.tex
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: auto build codebook - ${{ github.sha }}
