# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/docs.pdf'
      - 'pdf/codebook.pdf'
      - 'README.md'
      - '.editorconfig'

env:
  SOURCE_DATE_EPOCH: 0 # reproducible latex build

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  all:
    name: build and commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install codebook build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cpp latexmk texlive-lang-chinese texlive-science texlive-xetex make pandoc
      - name: Install codebook build Python dependencies
        working-directory: pdf
        run: pip install -r requirements.txt
      - name: Install docs build dependencies
      - name: Build codebook
        working-directory: pdf
        run: make clean && make codebook.pdf
      - name: Build docs
        working-directory: docs
        run: make clean && make docs.pdf
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: auto build - ${{ github.sha }}
